### ISSUE TITLE
Have the search box displayed in the subtitle-lines menu by default?

### ISSUE THREAD

**Issue by AziRizvi** [christoph-heinrich/mpv-subtitle-lines#11]
Once you've opened the subtitle-lines menu you have to press ctrl+f to trigger the search, is it possible to just have the search box just be there and activated by default? I don't want to have to press another key once the menu has been activated.

Here's an image that I've edited to showcase what I mean, when I open the subtitle-lines menu, this is what I would expect it to look like:

Thanks.

![Subtitle-Lines-Box](https://github.com/user-attachments/assets/089fcc01-94c5-431d-aace-47310150cab8)

**Comment by christoph-heinrich** [comment]
That menu follows whatever you've configured for uosc, how come you want it to be different to the other menus?

**Comment by AziRizvi** [comment]
I've just discovered that you only need to open the subtitles-lines menu and just start typing in words and that starts searching them, there isn't a need to press ctrl+f once the menu is open.
