### ISSUE TITLE
Ignore drawing commands & duplicate lines

### ISSUE THREAD

**Issue by FichteFoll** [christoph-heinrich/mpv-subtitle-lines#5]
I don't think drawing commands are within the scope of this script, so they should probably be skipped. Example:

![2024-02-26_23-25-58](https://github.com/christoph-heinrich/mpv-subtitle-lines/assets/931051/d3f90893-1cc4-4a1a-95f9-e3c9cb885b31)

**Comment by christoph-heinrich** [comment]
I'm not sure that's an issue of this script.

The `sub-text` property should only contain actual text that gets displayed. If other things appear in there then that's a problem of mpv or ffmpeg or libass (I don't know how the text is actually acquired in the code).

**Comment by christoph-heinrich** [comment]
I've had a quick look at the code and I think the problem is in https://github.com/mpv-player/mpv/blob/3e42139e138a8cbb67a756dab2d6eaeb2a115223/sub/sd_ass.c#L717-L763

I've never encountered that problem before, can you send a sample?

Edit: Inb4 there is a mistake in the subtitle text itself.

**Comment by FichteFoll** [comment]
Script LGTM (this is an excerpt; let me know if you need the full one)
```
[Script Info]
ScaledBorderAndShadow: yes
ScriptType: v4.00+
Collisions: Normal
PlayResX: 640
PlayResY: 360
Timer: 0.0000
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,26,&H00FFFFFF,&H000000FF,&H00000000,&HB4000000,-1,0,0,0,100,100,0,0,1,1.66667,0.333333,2,20,20,19,1
Style: TypePlaceholder,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,2,0,8,0010,0010,0020,1
Style: Top,Arial,26,&H00FFFFFF,&H000000FF,&H00000000,&HB4000000,-1,0,0,0,100,100,0,0,1,1.66667,0.333333,8,20,20,19,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 1,0:02:11.30,0:02:16.74,TypePlaceholder,,0000,0000,0000,,{\an1\fnVerdana\b1\fscx90\shad2\fs+1\b1\fsp1\c&HFCFEFE&\4c&HC7951D&\bord0\fad(206,0)\3c&HFFFFFE&\pos(138.26,298.44)}Bedauern liegt {\alpha&HFF&\t(331,498,\alpha&H00&)}immer {\alpha&HFF&\t(623,873,\alpha&H00&)}in der {\fnGeorgia Bold\fscx100\bord1\c&HC7951D&\3c&HFCFEFE&\4c&HFCFEFE&\alpha&HFF&\t(957,1749,\alpha&H00&)}Vergangenheit
Dialogue: 0,0:02:11.53,0:02:16.74,TypePlaceholder,,0000,0000,0000,,{\p1\c&HC7951D&\bord0\fad(101,0)\fscx530\fscy510\pos(334.5,309.5)}m 0 0 l -3 -7 l 11 -7 l 11 -2
Dialogue: 0,0:02:13.77,0:02:16.74,Top,Pencil Warrior,0000,0000,0000,,Dann lasst uns mal Kriegsrat halten.
Dialogue: 0,0:02:17.14,0:02:19.86,Default,Pencil Warrior,0000,0000,0000,,Problem Nummer eins\Nbeim Kampf gegen Wezaemon:
Dialogue: 0,0:02:19.86,0:02:22.12,TypePlaceholder,,0000,0000,0000,,{\fnTimes New Roman\b1\bord0\fax-0.5\an1\fs-3\c&H87867D&\frz6.688\pos(147,104)}\h\hGesammelte Informationen\Nüber Wezaemon
Dialogue: 0,0:02:20.42,0:02:22.12,Default,Pencil Warrior,0000,0000,0000,,Direkt zu Beginn des Kampfes …
```

Also note that there is actually only one line with drawing commands. I've noticed this a couple of times, actually, where some lines seem to be listed multiple times, which may very well be an mpv issue.

Edit: what it's supposed to look like:
![2024-02-27_01-46-01](https://github.com/christoph-heinrich/mpv-subtitle-lines/assets/931051/de0328e6-cdd6-4f89-8691-3fe308b93826)

Edit 2: mpv 0.37.0, mpv-subtitle-lines 1.1.0

**Comment by christoph-heinrich** [comment]
> Script LGTM (this is an excerpt; let me know if you need the full one)

Thanks, that excerpt was perfect for testing.

The draw commands were a bug in mpv.
I've also improved the line merging in this script and opened a pull request for testing.
