### ISSUE TITLE
Strip outward whitespace before displaying

### ISSUE THREAD

**Issue by FichteFoll** [christoph-heinrich/mpv-subtitle-lines#8]
Some subtitle lines are split like `first line\N second line`, which means there is technically a space character at the beginning of the second line but subtitle renderers ignore it and don't even consider it for alignment.

![image](https://github.com/christoph-heinrich/mpv-subtitle-lines/assets/931051/36df337d-7c17-4a70-b265-286937c1118c)

**Comment by christoph-heinrich** [comment]
I made a that PR works fine in my limited testing so far.

**Comment by FichteFoll** [comment]
Thanks. I doubt much testing will be necessary since the problem domain appears to be small. If you need a tester, I can only do so earliest next Monday.

**Comment by christoph-heinrich** [comment]
It's probably fine. I'll be using it over the next day or two and then merge.
